import type { AIDiscoveryCandidate } from './aiDiscovery'

const MOE_2022_MATH = 'https://www.moe.gov.cn/srcsite/A26/s8001/202204/W020220420582346895190.pdf'
const PEP_CN_G2X = 'https://www.pep.com.cn/products/zhytu/gjshnj/csxp/tbzc/202306/t20230627_1984161.shtml'
const PEP_CN_G3X = 'https://www.pep.com.cn/products/zhytu/gjshnj/csxp/tbzc/202306/t20230627_1984165.shtml'
const PEP_CN_G4X = 'https://www.pep.com.cn/products/zhytu/gjshnj/csxp/tbzc/202306/t20230628_1984167.shtml'
const PEP_CN_G5S = 'https://www.pep.com.cn/products/zhytu/gjshnj/csxp/tbzc/202306/t20230629_1984171.shtml'
const PEP_CN_G6S = 'https://www.pep.com.cn/products/zhytu/gjshnj/csxp/tbzc/202306/t20230630_1984178.shtml'
const PEP_EN_G4X = 'https://www.pep.com.cn/zslth/yyptzy/xypep/4x/'
const PEP_EN_G5S = 'https://www.pep.com.cn/zslth/yyptypzj/xypep/5s/'
const PEP_EN_G6S = 'https://www.pep.com.cn/zslth/yyptzy/xypep/6s/'

function candidate(input: Omit<AIDiscoveryCandidate, 'aiGenerated' | 'reviewStatus' | 'autoApply' | 'nextGate'>): AIDiscoveryCandidate {
  return {
    ...input,
    aiGenerated: true,
    reviewStatus: 'ai_candidate',
    autoApply: false,
    nextGate: 'human_ui_review',
  }
}

export const aiDiscoveryExpansion02Batch = {
  schema: 'qiqi-curriculum-ai-discovery-batch/v1' as const,
  batchId: 'ai-discovery-2026-09-09-wave02',
  generatedAt: '2026-09-09T14:05:00+08:00',
  note: '第二批优先补齐第一批 AI 搜索覆盖矩阵中的空白/浅覆盖年级。语文同步手册用于字词学习候选发现，当前教材版次仍需另行核验；英语使用人教社当前数字资源页；数学继续使用教育部2022课标。',
}

export const aiDiscoveryExpansion02: AIDiscoveryCandidate[] = [
  candidate({
    id: 'ai2-chinese-g2-word-pronunciation-writing',
    subject: 'chinese',
    grades: [2],
    candidateKind: 'knowledge_node',
    label: '字词准确读音与规范书写（二年级候选）',
    learningDemand: '结合课文识字与词语学习，准确读音并按规范笔顺书写本年级常用字词。',
    evidenceSummary: '人教社二年级下册同步字词手册说明其任务包括解释生词难词、辨析字词、巩固词语知识，并服务于规范书写与准确运用。',
    sourceRefs: [PEP_CN_G2X],
    sourceAuthority: 'publisher_catalog_version_unknown',
    sourceNote: '出版社2022年配套手册可支持候选方向，但不能据此认定为2026当前教材版次或完整学业要求。',
    confidence: 'medium',
  }),
  candidate({
    id: 'ai2-chinese-g2-similar-character-word',
    subject: 'chinese',
    grades: [2],
    candidateKind: 'knowledge_node',
    label: '音近词与形近词辨析（二年级候选）',
    learningDemand: '在具体词语和课文语境中辨析常见音近、形近字词，减少识写和使用混淆。',
    evidenceSummary: '人教社二年级下册同步字词手册明确包含音近词、形近词辨析。',
    sourceRefs: [PEP_CN_G2X],
    sourceAuthority: 'publisher_catalog_version_unknown',
    sourceNote: '配套资源直接支持“辨析”这一学习方向；具体字词清单仍需教材证据。',
    confidence: 'medium',
  }),
  candidate({
    id: 'ai2-chinese-g2-word-meaning-context',
    subject: 'chinese',
    grades: [2],
    candidateKind: 'knowledge_node',
    label: '词语意义与语境运用（二年级候选）',
    learningDemand: '理解常见词语在课文语境中的基本意义，并尝试在合适情境中准确使用。',
    evidenceSummary: '人教社二年级下册同步字词手册设置“理解·品味”“揣摩·运用”，强调词义、用法和语境中的表达效果。',
    sourceRefs: [PEP_CN_G2X],
    sourceAuthority: 'publisher_catalog_version_unknown',
    sourceNote: '候选粒度由AI归纳，需二年级语文教师确认是否应拆成理解与运用两个节点。',
    confidence: 'medium',
  }),
  candidate({
    id: 'ai2-chinese-g3-word-pronunciation-writing',
    subject: 'chinese',
    grades: [3],
    candidateKind: 'knowledge_node',
    label: '字词准确读音与规范书写（三年级候选）',
    learningDemand: '在三年级课文学习中持续提高常用字词的准确读音、规范书写和积累能力。',
    evidenceSummary: '人教社三年级下册同步字词手册以生词难词解释、字词辨析、训练强化为主要板块。',
    sourceRefs: [PEP_CN_G3X],
    sourceAuthority: 'publisher_catalog_version_unknown',
    sourceNote: '配套手册出版于2022年；教材版次和知识边界仍需真人核验。',
    confidence: 'medium',
  }),
  candidate({
    id: 'ai2-chinese-g3-synonym-near-synonym',
    subject: 'chinese',
    grades: [3],
    candidateKind: 'knowledge_node',
    label: '同义词与近义词用法辨析（三年级候选）',
    learningDemand: '结合课文语境比较常见同义、近义词在意义、语体和表达效果上的差别。',
    evidenceSummary: '人教社三年级下册同步字词手册明确提出结合课文辨析同义词、近义词和易错易混词语的用法与表达效果。',
    sourceRefs: [PEP_CN_G3X],
    sourceAuthority: 'publisher_catalog_version_unknown',
    sourceNote: '学习方向有出版社资源依据，具体词对和深度仍需教师确认。',
    confidence: 'medium',
  }),
  candidate({
    id: 'ai2-chinese-g3-word-expression-effect',
    subject: 'chinese',
    grades: [3],
    candidateKind: 'knowledge_node',
    label: '词语在语境中的表达效果（三年级候选）',
    learningDemand: '联系上下文理解有表现力词语的具体意义，并初步体会其表达作用。',
    evidenceSummary: '人教社三年级下册同步字词手册“理解·品味”板块明确关注熟词在课文语境中的意义和表达效果。',
    sourceRefs: [PEP_CN_G3X],
    sourceAuthority: 'publisher_catalog_version_unknown',
    sourceNote: 'AI只抽取学习方向，不转载教材正文；需真人判断与现有阅读节点是否语义重复。',
    confidence: 'medium',
  }),
  candidate({
    id: 'ai2-chinese-g4-word-usage-discrimination',
    subject: 'chinese',
    grades: [4],
    candidateKind: 'knowledge_node',
    label: '词义、用法与表达效果辨析（四年级候选）',
    learningDemand: '结合课文上下文辨析词语意义、用法和表达效果，支持更准确的阅读理解与表达。',
    evidenceSummary: '人教社四年级下册同步字词资源面向教材字词学习，可作为四年级词语运用能力候选入口。',
    sourceRefs: [PEP_CN_G4X],
    sourceAuthority: 'publisher_catalog_version_unknown',
    sourceNote: '具体能力描述为AI归纳，需核对手册/教材具体板块后才能进入精审。',
    confidence: 'low',
  }),
  candidate({
    id: 'ai2-chinese-g5-word-meaning-usage',
    subject: 'chinese',
    grades: [5],
    candidateKind: 'knowledge_node',
    label: '字词意义与用法辨析（五年级候选）',
    learningDemand: '在较复杂语境中理解重点词语意义，比较易混词用法并体会表达效果。',
    evidenceSummary: '人教社五年级上册同步字词手册以字词准确读音、偏旁作用、字词意义与用法讲解为特色。',
    sourceRefs: [PEP_CN_G5S],
    sourceAuthority: 'publisher_catalog_version_unknown',
    sourceNote: '配套手册是候选发现证据，不等于当前教材完整学习要求。',
    confidence: 'medium',
  }),
  candidate({
    id: 'ai2-chinese-g5-reading-books-theme',
    subject: 'chinese',
    grades: [5],
    candidateKind: 'textbook_theme',
    label: '读书方法与阅读经验表达（五年级候选）',
    learningDemand: '围绕阅读经历、读书方法和读书感受进行理解、交流与表达。',
    evidenceSummary: '人教社五年级上册配套目录第八单元连续出现《古人谈读书》《忆读书》《我的“长生果”》。',
    sourceRefs: [PEP_CN_G5S],
    sourceAuthority: 'publisher_catalog_version_unknown',
    sourceNote: '由单元选文组合推断主题，不能直接当作正式单元语文要素，必须真人查教材确认。',
    confidence: 'low',
  }),
  candidate({
    id: 'ai2-chinese-g5-ancient-text-vocabulary',
    subject: 'chinese',
    grades: [5],
    candidateKind: 'knowledge_node',
    label: '文言文常用实词与虚词初步积累（五年级候选）',
    learningDemand: '在文言文阅读中结合语境积累常用实词和虚词的基本意义与用法。',
    evidenceSummary: '人教社同步字词手册内容介绍明确提出讲解文言文常用实词和虚词、贯通古今。',
    sourceRefs: [PEP_CN_G5S],
    sourceAuthority: 'publisher_catalog_version_unknown',
    sourceNote: '配套资源支持该学习方向；具体词项、篇目和学段深度需教师核对。',
    confidence: 'medium',
  }),
  candidate({
    id: 'ai2-chinese-g6-ancient-text-vocabulary',
    subject: 'chinese',
    grades: [6],
    candidateKind: 'knowledge_node',
    label: '文言文常用实词与虚词积累（六年级候选）',
    learningDemand: '结合六年级文言文篇目理解并积累常用实词、虚词及其语境意义。',
    evidenceSummary: '人教社六年级上册目录含《文言文二则》，同步字词手册体系强调讲解文言文常用实词和虚词。',
    sourceRefs: [PEP_CN_G6S],
    sourceAuthority: 'publisher_catalog_version_unknown',
    sourceNote: '候选方向较明确，但正式词项和要求必须回到教材/课标核验。',
    confidence: 'medium',
  }),
  candidate({
    id: 'ai2-chinese-g6-poetry-image-rhythm',
    subject: 'chinese',
    grades: [6],
    candidateKind: 'knowledge_node',
    label: '古诗词常用意象与格律初步赏析（六年级候选）',
    learningDemand: '在古诗词阅读中积累常见意象，并初步关注诗词语言节奏、格律与表达效果。',
    evidenceSummary: '人教社六年级同步字词手册内容介绍提出赏析古诗词、积累常用意象、介绍诗词格律。',
    sourceRefs: [PEP_CN_G6S],
    sourceAuthority: 'publisher_catalog_version_unknown',
    sourceNote: '属于配套资源中的拓展方向，是否作为独立小学KnowledgeNode需真人慎审。',
    confidence: 'medium',
  }),
  candidate({
    id: 'ai2-chinese-g6-word-expression-effect',
    subject: 'chinese',
    grades: [6],
    candidateKind: 'knowledge_node',
    label: '词语语境意义与表达效果（六年级候选）',
    learningDemand: '在复杂文本语境中准确理解重点词语含义，比较其用法并分析表达效果。',
    evidenceSummary: '人教社同步字词手册体系包含“理解·品味”和“揣摩·运用”，强调语境意义、语体和表达效果。',
    sourceRefs: [PEP_CN_G6S],
    sourceAuthority: 'publisher_catalog_version_unknown',
    sourceNote: 'AI归纳的能力节点，需与现有阅读鉴赏节点做语义重复核查。',
    confidence: 'medium',
  }),
  candidate({
    id: 'ai2-english-g4-rules-responsibility',
    subject: 'english',
    grades: [4],
    candidateKind: 'communication_function',
    label: '班级与家庭规则表达（四年级候选）',
    learningDemand: '围绕班级和家庭规则进行基本交流，理解规则主题中的常见表达和行为要求。',
    evidenceSummary: '人教社四年级下册当前数字资源连续设置 Unit 1 Class rules 与 Unit 2 Family rules，并包含 Let’s talk / Read and write。',
    sourceRefs: [PEP_EN_G4X],
    sourceAuthority: 'publisher_current_resource',
    sourceNote: '主题和交际场景有当前资源依据；具体语法/句型需打开教材内容后精审。',
    confidence: 'medium',
  }),
  candidate({
    id: 'ai2-english-g4-time-school',
    subject: 'english',
    grades: [4],
    candidateKind: 'communication_function',
    label: '学校时间与日程交流（四年级候选）',
    learningDemand: '在学校生活情境中理解和交流时间、日程或相关活动安排。',
    evidenceSummary: '人教社四年级下册当前资源设置 Unit 3 Time for school，并配置口语、听做、读写活动。',
    sourceRefs: [PEP_EN_G4X],
    sourceAuthority: 'publisher_current_resource',
    sourceNote: '由明确单元主题归纳交际功能；具体时态/句式不由AI自动补全。',
    confidence: 'medium',
  }),
  candidate({
    id: 'ai2-english-g4-shopping',
    subject: 'english',
    grades: [4],
    candidateKind: 'communication_function',
    label: '购物情境中的基本交流（四年级候选）',
    learningDemand: '在购物情境中进行基本询问、选择或回应，理解相关常用表达。',
    evidenceSummary: '人教社四年级下册当前资源设置 Unit 4 Going shopping，并包含 Let’s talk / Read and write。',
    sourceRefs: [PEP_EN_G4X],
    sourceAuthority: 'publisher_current_resource',
    sourceNote: '交际主题明确；价格、数量等具体功能项必须由教材内容确认。',
    confidence: 'medium',
  }),
  candidate({
    id: 'ai2-english-g5-person-description',
    subject: 'english',
    grades: [5],
    candidateKind: 'communication_function',
    label: '人物特征描述（五年级候选）',
    learningDemand: '围绕熟悉人物的外貌、性格或特点进行简单询问和描述。',
    evidenceSummary: '人教社五年级上册资源设置 Unit 1 What’s he like?，并配置 Let’s talk / Let’s learn / Read and write。',
    sourceRefs: [PEP_EN_G5S],
    sourceAuthority: 'publisher_current_resource',
    sourceNote: '主题功能较清楚；具体形容词范围和问答句型需真人核对。',
    confidence: 'medium',
  }),
  candidate({
    id: 'ai2-english-g5-week-schedule',
    subject: 'english',
    grades: [5],
    candidateKind: 'communication_function',
    label: '一周安排与活动交流（五年级候选）',
    learningDemand: '围绕一周中的课程、活动或日常安排进行简单交流和描述。',
    evidenceSummary: '人教社五年级上册资源设置 Unit 2 My week，并包含口语、拼读和读写活动。',
    sourceRefs: [PEP_EN_G5S],
    sourceAuthority: 'publisher_current_resource',
    sourceNote: '由单元主题归纳；频率副词等更细语言知识不自动推断。',
    confidence: 'medium',
  }),
  candidate({
    id: 'ai2-english-g5-food-preference-request',
    subject: 'english',
    grades: [5],
    candidateKind: 'communication_function',
    label: '饮食偏好与请求表达（五年级候选）',
    learningDemand: '在饮食情境中表达简单偏好、询问需求并进行基本回应。',
    evidenceSummary: '人教社五年级上册资源设置 Unit 3 What would you like?，并包含 Let’s talk / Read and write。',
    sourceRefs: [PEP_EN_G5S],
    sourceAuthority: 'publisher_current_resource',
    sourceNote: '功能方向由单元标题直接支持；具体词汇/句型需教师精审。',
    confidence: 'medium',
  }),
  candidate({
    id: 'ai2-english-g6-social-gathering',
    subject: 'english',
    grades: [6],
    candidateKind: 'textbook_theme',
    label: '聚会与共同活动主题交流（六年级候选）',
    learningDemand: '围绕聚会、共同活动或社交场景理解和交流基本信息。',
    evidenceSummary: '人教社六年级上册当前资源设置 Unit 2 Getting together。',
    sourceRefs: [PEP_EN_G6S],
    sourceAuthority: 'publisher_current_resource',
    sourceNote: '目前仅有单元主题证据，具体交际功能需要进入教材页面后再拆分。',
    confidence: 'low',
  }),
  candidate({
    id: 'ai2-math-g5-6-data-collect-express',
    subject: 'math',
    grades: [5, 6],
    candidateKind: 'knowledge_domain',
    label: '数据的收集、整理与表达（第三学段）',
    learningDemand: '在第三学段继续经历数据收集、整理、表达和解释过程，并与随机现象学习形成统计与概率领域主线。',
    evidenceSummary: '教育部2022数学课程标准在第三学段统计与概率中继续设置数据的收集、整理与表达，并增加随机现象发生的可能性。',
    sourceRefs: [MOE_2022_MATH],
    sourceAuthority: 'official_standard_2022',
    sourceNote: '官方课标领域锚点；不对应单一教材章节。',
    confidence: 'high',
  }),
]
